version: '3'

networks:
  cloudflare:
    external: true

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    hostname: cloudflared-tunnel
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      cloudflare:
    volumes:
      - /var/caddy/cloudflared:/etc/cloudflared

  ubuntu-test:
    image: ubuntu:latest
    command: tail -f /dev/null
    networks:
        cloudflare:

  server:
    build: .
    container_name: caddy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /var/caddy/data:/data
      - /var/caddy/config:/config
      - /var/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/caddy/www:/var/www:ro
    restart: always
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      ACME_AGREE: 'true'
    hostname: server
    networks:
      cloudflare:
