version: '3'

networks:
  cloudflare:
    external: true

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    hostname: cloudflared-tunnel
    command: tunnel run
    restart: always
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      cloudflare:

  caddy:
    build: .
    container_name: caddy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - caddyfile:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - /var/caddy/www:/var/www:ro
    restart: always
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      ACME_AGREE: 'true'
    hostname: caddy
    networks:
      cloudflare:
